Update python-publish.yml

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -1,4 +1,4 @@
-name: Upload Python Package
+name: Upload Python Package with Tag Release
 
 on:
   push:
@@ -14,29 +14,46 @@ jobs:
         python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
 
     steps:
-    - uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Install dependencies and build package
-      run: |
-        python -m pip install --upgrade pip
-        pip install wheel Cython setuptools
-        python setup.py bdist_wheel
+      - name: Install dependencies and build package
+        run: |
+          python -m pip install --upgrade pip
+          pip install wheel Cython setuptools
+          python setup.py bdist_wheel
+        continue-on-error: true
+        shell: bash
 
-    - name: Create Release
-      id: create_release
-      uses: softprops/action-gh-release@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        files: dist/*
+      - name: Check if package is built
+        run: |
+          if [ ! -f "dist/*.whl" ]; then
+            echo "Error: Python package not found"
+            exit 1
+          fi
+        shell: bash
 
-    - name: Publish to PyPI
-      uses: pypa/gh-action-pypi-publish@v1.9.0
-      with:
-        user: __token__
-        password: ${{ secrets.PYPI_API_TOKEN }}
+      - name: Create Release
+        id: create_release
+        if: success()
+        uses: softprops/action-gh-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: v1.0.3  # 指定你要创建的 tag 名称，可以根据需要修改
+          release_name: Release v1.0.3  # 标签的显示名称
+          body: |
+            Release notes for version 1.0.3 go here.  # 发布说明
+          files: dist/*
+
+      - name: Publish to PyPI
+        if: success()
+        uses: pypa/gh-action-pypi-publish@v1.9.0
+        with:
+          user: __token__
+          password: ${{ secrets.PYPI_API_TOKEN }}
